# This is only used for documentation generation in Roadie. It is not part of the vertex started kit.

site_name: Vertex pipelines starter kit
repo_name: artefactory/vertex-pipeline-starter-kit
repo_url: https://github.com/artefactory/vertex-pipeline-starter-kit

plugins:
  - techdocs-core

nav:
  - Vertex pipeline starter kit: index.md
  - 🚧 Rules of thumb to split components: splitting_components.md
  - 🚧 Managing python packages and dependencies: managing_packages.md
  - 🚧 Managing pipelines configurations: managing_pipeline_configuration.md
  - 🚧 Parallelizing processings in pipelines: parallelizing_processing.md
  - 🚧 Scheduling pipelines: scheduling_pipelines.md
  - 🚧 Using premade components: when_to_use_premade_components.md